---
{{- if not .Values.disableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    {{- if .Values.validatingWebhookAnnotations }}
    {{- toYaml .Values.validatingWebhookAnnotations | trim | nindent 4 }}
    {{- end }}
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: '{{ .Values.validatingWebhookName }}'
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    {{- if .Values.validatingWebhookURL }}
    url: https://{{ .Values.validatingWebhookURL }}/v1/admit
    {{- else }}
    service:
      name: gatekeeper-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /v1/admit
    {{- end }}
  failurePolicy: {{ .Values.validatingWebhookFailurePolicy }}
  matchPolicy: Exact
  name: validation.gatekeeper.sh
  namespaceSelector:
    matchExpressions:
    - key: admission.gatekeeper.sh/ignore
      operator: DoesNotExist
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - {{ .Release.Namespace }}
    {{- range $key, $value := .Values.validatingWebhookExemptNamespacesLabels }}
    - key: {{ $key }}
      operator: NotIn
      values:
      {{- range $value }}
      - {{ . }}
      {{- end }}
    {{- end }}
  objectSelector: {{- toYaml .Values.validatingWebhookObjectSelector | nindent 4 }}
  {{- if .Values.validatingWebhookMatchConditions }}
  {{- if ge (int .Capabilities.KubeVersion.Minor) 28 }}
  matchConditions: {{- toYaml .Values.validatingWebhookMatchConditions | nindent 4 }}
  {{- end }}
  {{- end }}
  rules:
  {{- if .Values.validatingWebhookCustomRules }}
  {{- toYaml .Values.validatingWebhookCustomRules | nindent 2 }}
  {{- else }}
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    {{- if .Values.enableDeleteOperations }}
    - DELETE
    {{- end }}
    {{- if .Values.enableConnectOperations }}
    - CONNECT
    {{- end }}
    resources:
    - '*'
    {{- range .Values.validatingWebhookSubResources }}
    - {{ . }}
    {{- end }}
    scope: '{{ .Values.validatingWebhookScope }}'
  {{- end }}
  sideEffects: None
  timeoutSeconds: {{ .Values.validatingWebhookTimeoutSeconds }}
{{- end }}
