{{- if not .Values.disableMutation }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    {{- if .Values.mutatingWebhookAnnotations }}
    {{- toYaml .Values.mutatingWebhookAnnotations | trim | nindent 4 }}
    {{- end }}
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: '{{ .Values.mutatingWebhookName }}'
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    {{- if .Values.mutatingWebhookURL }}
    url: https://{{ .Values.mutatingWebhookURL }}/v1/mutate
    {{- else }}
    service:
      name: gatekeeper-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /v1/mutate
    {{- end }}
  failurePolicy: {{ .Values.mutatingWebhookFailurePolicy }}
  matchPolicy: Exact
  name: mutation.gatekeeper.sh
  sideEffects: None
  timeoutSeconds: {{ .Values.mutatingWebhookTimeoutSeconds }}
{{- end }}

